document.addEventListener('DOMContentLoaded', () => {
    initApp();
});

let APP_CONFIG = {};
let COLLECTION_DATA = []; 

async function initApp() {
    console.log("Initializing Luxury Store...");
    
    // 1. Get the CSV Links (generated by build.js)
    try {
        const configRes = await fetch('config.json');
        if (!configRes.ok) throw new Error("Config missing");
        APP_CONFIG = await configRes.json();
    } catch (e) {
        console.error("⚠️ Config load failed. Is build.js running?", e);
        return; 
    }

    // 2. Load Everything in Parallel
    await Promise.all([
        loadTheme(APP_CONFIG.theme_csv),
        loadImagesAndHTML(),
        loadSocialLinks(APP_CONFIG.links_csv),
        loadCollections(APP_CONFIG.collections_csv)
    ]);
}

/* --- THEME ENGINE (Matches your Theme CSV screenshot) --- */
async function loadTheme(csvUrl) {
    if(!csvUrl) return;
    const rows = await fetchCSV(csvUrl);
    // Rows[0] is Header. Randomize 1 to End.
    if(rows.length < 2) return;

    const randomIndex = Math.floor(Math.random() * (rows.length - 1)) + 1;
    const theme = rows[randomIndex]; // [ID, Bg, Text, Accent, BtnBg, BtnText, Font]

    if(theme) {
        const root = document.documentElement;
        root.style.setProperty('--bg-color', theme[1]);
        root.style.setProperty('--text-color', theme[2]);
        root.style.setProperty('--accent-color', theme[3]);
        root.style.setProperty('--btn-bg', theme[4]);
        root.style.setProperty('--btn-text', theme[5]);
        if(theme[6]) document.body.style.fontFamily = theme[6];
    }
}

/* --- SOCIAL LINKS (Matches your Links CSV screenshot) --- */
async function loadSocialLinks(csvUrl) {
    if(!csvUrl) return;
    const rows = await fetchCSV(csvUrl);
    
    const checkHeader = setInterval(() => {
        const container = document.querySelector('.social-icons');
        if(container) {
            clearInterval(checkHeader);
            let html = '';
            // Start at 1 to skip header. 
            // CSV Structure: [0]Key, [1]Label, [2]Link_URL, [3]Icon_Class
            for(let i=1; i<rows.length; i++) {
                const row = rows[i];
                if(row[2] && row[3]) { // Ensure Link and Icon exist
                    html += `<a href="${row[2]}" target="_blank" class="icon-btn" aria-label="${row[1]}">
                                <i class="fa-brands ${row[3]}"></i>
                             </a>`;
                }
            }
            container.innerHTML = html;
        }
    }, 100);
}

/* --- COLLECTIONS (Matches your Collections CSV screenshot) --- */
async function loadCollections(csvUrl) {
    if(!csvUrl) return;
    const rows = await fetchCSV(csvUrl);
    
    // CSV Structure: [0]Category_Name, [1]Image_Filename, [2]External_Link
    // We skip row 0 (Header)
    COLLECTION_DATA = rows.slice(1).map(r => ({ 
        name: r[0], 
        img: r[1], 
        link: r[2] 
    })).filter(item => item.name); // Filter out empty lines

    const checkGrid = setInterval(() => {
        const grid = document.querySelector('.collection-preview-grid');
        if(grid) {
            clearInterval(checkGrid);
            let html = '';
            // Show first 4 items on home page
            COLLECTION_DATA.slice(0, 4).forEach(item => {
                html += createCollectionCard(item);
            });
            grid.innerHTML = html;
        }
    }, 100);
}

function createCollectionCard(item) {
    const imgPath = `assets/collections/${item.img.trim()}`; // Trims spaces from filename
    // If link is empty, make it non-clickable or point to #
    const linkUrl = item.link ? item.link : '#';
    
    return `
        <a href="${linkUrl}" target="_blank" class="collection-card">
            <img src="${imgPath}" loading="lazy" alt="${item.name}">
            <span>${item.name}</span>
        </a>
    `;
}

/* --- IMAGES & HTML SECTIONS --- */
async function loadImagesAndHTML() {
    // 1. Get File List
    let manifest = {};
    try {
        const res = await fetch('manifest.json');
        manifest = await res.json();
    } catch(e) { console.log("Manifest loading..."); }

    // 2. Load HTML Snippets
    const sections = ['header', 'about', 'how_to_order', 'collections', 'testimonials', 'vendor_access', 'delivery_proof', 'payment_proof'];
    
    for (const section of sections) {
        try {
            const res = await fetch(`sections/${section}.html`);
            const html = await res.text();
            const el = document.getElementById(`${section}-section`);
            if(el) {
                el.innerHTML = html;
                
                // Inject Images based on section
                if(section === 'header' && manifest.profile_images) {
                    const randomProfile = manifest.profile_images[Math.floor(Math.random() * manifest.profile_images.length)];
                    document.getElementById('dynamic-profile-img').src = `assets/profile/${randomProfile}`;
                }
                if(section === 'testimonials') populateMarquee('testimonials-track', manifest.testimonials, 'assets/testimonials/');
                if(section === 'delivery_proof') populateMarquee('delivery-track', manifest.delivery_proofs, 'assets/delivery_proofs/');
                if(section === 'payment_proof') populateMarquee('payment-track', manifest.payment_proofs, 'assets/payment_proofs/');
            }
        } catch(e) {}
    }
}

function populateMarquee(elementId, images, basePath) {
    const track = document.getElementById(elementId);
    if(!track || !images || images.length === 0) return;
    let html = '';
    images.forEach(img => {
        html += `<img src="${basePath}${img}" onclick="openZoom(this.src)" class="marquee-img" loading="lazy">`;
    });
    track.innerHTML = html + html; // Duplicate for loop
}

/* --- MODALS --- */
function toggleCollectionModal(show) {
    const modal = document.getElementById('collection-modal');
    const grid = document.getElementById('modal-grid-container');
    
    if(show) {
        let html = '';
        COLLECTION_DATA.forEach(item => html += createCollectionCard(item));
        grid.innerHTML = html;
        modal.classList.remove('hidden');
        document.body.style.overflow = 'hidden';
    } else {
        modal.classList.add('hidden');
        document.body.style.overflow = 'auto';
    }
}

function openZoom(src) {
    document.getElementById('image-zoom-modal').classList.remove('hidden');
    document.getElementById('img01').src = src;
}
function closeZoom() {
    document.getElementById('image-zoom-modal').classList.add('hidden');
}

/* --- CSV PARSER (Handles quoted commas roughly) --- */
async function fetchCSV(url) {
    try {
        const res = await fetch(url);
        const text = await res.text();
        const rows = [];
        text.split('\n').forEach(line => {
            // Simple split by comma (assuming no commas INSIDE the text content)
            const cols = line.split(',');
            if(cols.length > 1) rows.push(cols);
        });
        return rows;
    } catch(e) { return []; }
}